package String;

import java.io.UnsupportedEncodingException;
import java.util.Arrays;

/** ---------------------------------------------
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add 
 * one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 --------------------------------------------- */
/* ---------------------------------------------
 * Simple O(n) solution
 * --------------------------------------------- */
public class FindTheDifference {
	public static char findTheDiff(String s, String t) {
		int freq[] = new int[26];
		
		for (int i = 0; i<t.length();i++) {
			freq[(int)(t.charAt(i) - 'a')]++;
			if (i < s.length()){
				freq[(int)(s.charAt(i) - 'a')]--;
			}
		}
		
		for (int i = 0 ;i<t.length();i++) {
			if (freq[i] != 0) {
				return (char)(i + 'a');
			}
		}
		return 0;
	}
	
/* -------------------------
 * Using bit Manipulation
 *------------------------*/

public static void findTheDiff_2() throws UnsupportedEncodingException {
	String x = "abcd";
	String y = "abcde";
	char c = y.charAt(x.length() -1);
	
	for (int i = 0 ; i<y.length()-1;i++) {
		System.out.println("xxxx:" + Integer.toBinaryString(x.charAt(i)));
		System.out.println("YYYY:" + Integer.toBinaryString(y.charAt(i)));
		System.out.println("CCCC:" + Integer.toBinaryString(c));
		c = (char) (c^x.charAt(i));
		System.out.println("FIRST C:" + Integer.toBinaryString(c));
		c = (char) (c^y.charAt(i));
		System.out.println("Seconde c:" + Integer.toBinaryString(c));
	}
	System.out.println(c);
	
	//System.out.println((int) ch3 + " UTF-8 encoded is " + Arrays.toString(String.valueOf(ch3).getBytes("UTF-8")));
}
 
	public static void main(String[] args) throws UnsupportedEncodingException {
		String s = "abcd";
		String t = "abecd";
		System.out.println(findTheDiff(s,t));
		//findTheDiff_2();
	} 
	
}
